server:
  port: 7900
spring:
  datasource:
    url: jdbc:mysql://10.0.0.200:3306/sping-cloud-demo?useUnicode=true&characterEncoding=UTF-8
    username: shiyue
    password: shiyue
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
      hibernate:
        ddl-auto: none #每次启动时不根据实体自动构建数据库结构
        naming:
          strategy: org.hibernate.cfg.ImprovedNamingStrategy #实体和表的映射策略
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect  #数据库方言
      show-sql: true
  application:
    name: microservice-provider-user           #虚拟IP名称 virtual Ip
  #zipkin:
    #base-url: http://127.0.0.1:7788
#日志配置开始
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
#日志配置结束
#eureka配置开始
eureka:
  client:
    healthcheck:
      enabled: true            # 开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://admin:admin@peer1:8761/eureka/,http://admin:admin@peer2:8762/eureka/,http://admin:admin@peer3:8763/eureka/
  instance:
    prefer-ip-address: true                   # 开启健康检查（需要spring-boot-starter-actuator依赖）
    lease-expiration-duration-in-seconds: 90  #续约到期时间(单位 S)默认是90S
    lease-renewal-interval-in-seconds: 30     # 续约更新时间间隔（默认30秒）
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      zone: ABC      # eureka可以理解的元数据
      lilizhou: BBC  # 不会影响客户端行为
#eureka配置结束